version: '3.8'

services:
  database:
    image: mysql:5.7
    restart: always
    env_file:
      - ./env/database.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - template-network

  backend:
    build: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - database
    networks:
      - template-network

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  db_volume:

networks:
  template-network:
